spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/notification_platform
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  data:
    redis:
      url : redis://localhost:6379